name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE]: "
labels: ["enhancement", "needs-review"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! ✨
        
        Please provide as much detail as possible to help us understand your request.

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Core RAG Functionality
        - Predictive Intelligence
        - Context Optimization (CAPE)
        - Knowledge Graphs
        - User Interface
        - API Enhancements
        - Performance
        - Security
        - Documentation
        - Developer Experience
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe alternatives you've considered
      placeholder: "I also considered..."

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - "Critical - Blocking my work"
        - "High - Important for next release"
        - "Medium - Nice to have soon"  
        - "Low - Future consideration"
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to contribute to implementing this feature
        - label: I can provide testing for this feature
        - label: I can provide documentation for this feature
