networks:
  ardharag_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  qdrant_data:
    driver: local
  redis_data:
    driver: local

services:
  postgres:
    image: apache/age:latest
    container_name: ardharag_postgres
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1536M
          cpus: '1.0'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/01-init-age.sql:/docker-entrypoint-initdb.d/01-init-age.sql:ro
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - ardharag_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant:latest
    container_name: ardharag_qdrant
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2048M
          cpus: '1.0'
    volumes:
      - qdrant_data:/qdrant/storage
      - ./qdrant/production.yaml:/qdrant/config/production.yaml:ro
    ports:
      - "127.0.0.1:6333:6333"
      - "127.0.0.1:6334:6334"
    networks:
      - ardharag_network
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:7.2.4-alpine
    container_name: ardharag_redis
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: '0.5'
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - ardharag_network
    command: redis-server /usr/local/etc/redis/redis.conf --maxmemory 768mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
    depends_on:
      postgres:
        condition: service_healthy
